language: node_js
node_js:
  - 16

install:
  - yarn install

script:
  - yarn build

after_success:
  - ls ./dist
  - tar -zcf dist.tar.gz ./dist
  - curl -T dist.tar.gz -u ${CODING_USER}:${CODING_PWD} "https://virola-generic.pkg.coding.net/mytools/files/genshin-dist.tar.gz?version=latest"

branches:
  only:
    - main
